version: '3.9'

services:
  app:
    image: python:3.10.13-alpine
    ports:
      - "9089:8089"
    volumes:
      - type: bind
        source: .
        target: /app
    restart: unless-stopped
    command: sh -c "apk add --no-cache dcron && \
      pip install -r /app/requirements.txt && \
      chmod +x /app/src/update_script.sh && \
      echo '0 7 * * 3 /app/src/update_script.sh >> /app/out-update.txt' > /etc/crontabs/root && \
      crond -b && \
      python /app/main.py"